title: FedGeoDay
year: 2021
email: help@osgeo.us
description: "Open Source Geospatial in the Federal Government"


sass:
  sass_dir: _sass
  style: compressed

exclude: ["Gemfile", "README.md"]

baseurl:

# the base hostname & protocol for your site
url: https://fedgeo.us

####################################
######   Optional Features    ######
####################################
smooth-scroll: false

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

#######################################################
#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################
#######################################################

# Website language
lang: en-US
# Header Title
header-title: FedGeoDay 2021
# Header Tagline
header-tagline: Open Source Geospatial in the Federal Government

####################################
######   CTA Header Buttons   ######
####################################

# Focus Buttons
header-focus-button:
  title: Watch the Videos
  url: https://vimeo.com/showcase/8599516

# Secondary Buttons
header-secondary-button:
  title: Watch
  url: 


# Offer Banner Link
# Default link is a link to all Sera OnePage products
banner-link: https://themeforest.net/collections/6069390-sera

####################################
######  Global Social Links   ######
####################################
youtube: '#'
pinterest: '#'
facebook: '#'
twitter: '#'
google-plus: '#'
vimeo: '#'

#########################
######   Widgets   ######
#########################

#
# About Blog Author Widget
#
about-widget:
  author-avatar: avatar-02.webp
  author-name: John Doe
  author-tagline: Blog Author
  author-info: Cum sociis que penatibus et magnis dis parturient montes lorem, nascetur ridiculus mus. Donec quam felis, ultricies.
  author-social-links:
    youtube: '#'
    pinterest: '#'
    facebook: '#'
    twitter: '#'
    google-plus: '#'

# Google Map JS api
# This is my api for this template
key-api: AIzaSyDbnxVZQannH0GF4gtnnBFPiP9ofm2WqGs
map-text: Sera Google Map
map-text-location: Bucharest, Romania
map-lat: 44.4267674
map-lng: 26.102538399999958

# Enter your Mailchimp User ID and Campaign ID
# @TODO: Add in a link for where to find these
mailchimp:
  user-id: REPLACEME
  list-id: REPLACEME

####
#
# Hi you now use Sera - OnePage Jekyll Template created by Gleesik™
#
# Below are each section from the website in order from top to bottom
# @TODO Edit each sections with your real information and each section from Sera will autocomplete with your information
#
####

#####################################
#############   About   #############
#####################################
about-title: FedGeoDay 2021
about-description: FedGeoDay is THE event devoted to "open geospatial ecosystems" (open source software, open/collaborative mapping, open science challenges and open engagements) that are used to initiate and grow capabilities across the U.S. federal government. This live, online conference brings together federal program managers, technology leaders, industry partners, NGOs, and many others to gather and share ideas, learn, and network.


#####################################
#############  Features  ############
#####################################
features-title: Features
features-description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante.

#
# Features
#
features:

# Feature
- title: June 8 "Program Day" 
  description: Plenary presentations, panel discussions, and lightning talks by leading experts.
  icon: pe-7s-vector

# Feature
- title: June 9 “Hands On Day”
  description: Extensive set of training opportunities on leading open source technologies.
  icon: pe-7s-help2

# Feature
- title: Community Conversation 
  description: Ask speakers questions and join the conversation!
  icon: pe-7s-airplay

#####################################
##########  Core Features  ##########
#####################################
core-title: Core Features
core-description: Duis at odio vitae ex gravida volutpat. Nulla finibus aliquet diam ut eleifend. Mauris consequat interdum quam. Mauris dui sapien, efficitur et cursus id, molestie fringilla turpis aliquet diam ut eleifend.

#
# Core Features Left
#
core-features-left:

# Feature
- name: Creative
  description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
  icon: pe-7s-light

# Feature
- name: Minimalism
  description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
  icon: pe-7s-drop

# Feature
- name: Clean Coding
  description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
  icon: pe-7s-coffee

# Feature
- name: Friendly
  description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
  icon: pe-7s-smile

#
# Core Features Right
#
core-features-right:

# Feature
- name: Branding
  description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
  icon: pe-7s-wine

# Feature
- name: Web Design
  description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
  icon: pe-7s-monitor

# Feature
- name: Graphic Design
  description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
  icon: pe-7s-crop

# Feature
- name: Photography
  description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
  icon: pe-7s-camera


#####################################
########### Testimonials ############
#####################################
testimonials-title: Testimonials
testimonials-description: Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi.

#
# Testimonials
#
testimonials:

# Client
- name: Johnatan Doe
  url: http://themeforest.net
  url-text: ThemeForest.net
  avatar: avatar-01.webp
  cite: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius adipiscing lectus, eu ornare lectus semper in. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed.
  logo-img: themeforest.webp

# Client
- name: Adam Smith
  url: http://codecanyon.net
  url-text: CodeCanyon.net
  avatar: avatar-02.webp
  cite: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius adipiscing lectus, eu ornare lectus semper in. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed.
  logo-img: codecanyon.webp

# Client
- name: Irene Warner
  url: http://videohive.net
  url-text: VideoHive.net
  avatar: avatar-03.webp
  cite: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius adipiscing lectus, eu ornare lectus semper in. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed.
  logo-img: videohive.webp

# Client
- name: Richard Ryan
  url: http://audiojungle.net
  url-text: AudioJungle.net
  avatar: avatar-04.webp
  cite: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius adipiscing lectus, eu ornare lectus semper in. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed.
  logo-img: audiojungle.webp


#####################################
############# Our Blog ##############
#####################################
blog-title: Our Blog
blog-description: Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi. Nulla a tellus at turpis gravida congue non sed nisl. Pellentesque scelerisque eu neque et tincidunt.


#####################################
############### Team ################
#####################################
team-title: Meet Our Team
team-description: The Organizing Committee are volunteers dedicated to promoting open source geospatial and mapping technology.


#####################################
########## Pricing Tables ###########
#####################################
pricing-title: Pricing Tables
pricing-description: Nulla a tellus at turpis gravida congue non interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi. Nulla a tellus at turpis gravida congue non sed nisl. Pellentesque scelerisque eu neque et tincidunt.

#
# Plan Personal
#
plan-personal-price: $99
plan-personal-offer-1-title: 01 PSD Pack
plan-personal-offer-1-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-personal-offer-2-title: 100 Support Tickets
plan-personal-offer-2-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-personal-url: '#'

#
# Plan Business
#
plan-business-price: $499
plan-business-offer-1-title: 05 PSD Pack
plan-business-offer-1-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-business-offer-2-title: 1000 Support Tickets
plan-business-offer-2-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-business-url: '#'

#
# Plan Ultimate
#
plan-ultimate-price: $999
plan-ultimate-offer-1-title: 10 PSD Pack
plan-ultimate-offer-1-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-ultimate-offer-2-title: Support Unlimited
plan-ultimate-offer-2-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-ultimate-url: '#'


#####################################
############   Contact   ############
#####################################
contact-title: Contact Us
contact-description: Nulla a tellus at turpis gravida congue non interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat.


#####################################
#############   Footer   ############
#####################################
footer-description: Nulla a tellus at turpis gravida congue non interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat.
footer-copyright-text: Gleesik&trade;
footer-copyright-url: http://gleesik.ro/
footer-copyright-year: 2016
